version: '3.8'

services:
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - ./redis-data:/data

  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      - redis