version: '3.8'

services:
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - ./redis-data:/data

  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis